# Generated by Django 5.1.1 on 2024-11-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_avatar.jpg', null=True, upload_to='user_images'),
        ),
    ]
