# Generated by Django 5.1.3 on 2024-11-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_blockactive_alter_userprofile_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="wallet_credentials",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
