# Generated by Django 5.1.3 on 2024-12-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile_wallet_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="wallet_credentials",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="wallet_hashes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
